deckOfCards = {
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9,
    "10": 10,
    "J": 10,
    "Q": 10,
    "K": 10,
    "A": 11
}
hardTotalDict = {
    20: {
    2: "STAND",
    3: "STAND",
    4: "STAND",
    5: "STAND",
    6: "STAND",
    7: "STAND",
    8: "STAND",
    9: "STAND",
    10: "STAND",
    11: "STAND",
    },
    19: {
    2: "STAND",
    3: "STAND",
    4: "STAND",
    5: "STAND",
    6: "STAND",
    7: "STAND",
    8: "STAND",
    9: "STAND",
    10: "STAND",
    11: "STAND",
    },
    18: {
    2: "STAND",
    3: "STAND",
    4: "STAND",
    5: "STAND",
    6: "STAND",
    7: "STAND",
    8: "STAND",
    9: "STAND",
    10: "STAND",
    11: "STAND",
    },
    17: {
    2: "STAND",
    3: "STAND",
    4: "STAND",
    5: "STAND",
    6: "STAND",
    7: "STAND",
    8: "STAND",
    9: "STAND",
    10: "STAND",
    11: "STAND",
    },
    16: {
    2: "STAND",
    3: "STAND",
    4: "STAND",
    5: "STAND",
    6: "STAND",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT",
    },
    15: {
    2: "STAND",
    3: "STAND",
    4: "STAND",
    5: "STAND",
    6: "STAND",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT",
    },
    14: {
    2: "STAND",
    3: "STAND",
    4: "STAND",
    5: "STAND",
    6: "STAND",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT",
    },
    13: {
    2: "STAND",
    3: "STAND",
    4: "STAND",
    5: "STAND",
    6: "STAND",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT",
    },
    12: {
    2: "HIT",
    3: "HIT",
    4: "STAND",
    5: "STAND",
    6: "STAND",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT",
    },
    11: {
    2: "DOUBLE DOWN",
    3: "DOUBLE DOWN",
    4: "DOUBLE DOWN",
    5: "DOUBLE DOWN",
    6: "DOUBLE DOWN",
    7: "DOUBLE DOWN",
    8: "DOUBLE DOWN",
    9: "DOUBLE DOWN",
    10: "DOUBLE DOWN",
    11: "DOUBLE DOWN",
    },
    10: {
    2: "DOUBLE DOWN",
    3: "DOUBLE DOWN",
    4: "DOUBLE DOWN",
    5: "DOUBLE DOWN",
    6: "DOUBLE DOWN",
    7: "DOUBLE DOWN",
    8: "DOUBLE DOWN",
    9: "DOUBLE DOWN",
    10: "HIT",
    11: "HIT",
    },
    9: {
    2: "HIT",
    3: "DOUBLE DOWN",
    4: "DOUBLE DOWN",
    5: "DOUBLE DOWN",
    6: "DOUBLE DOWN",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT",
    },
    8: {
    2: "HIT",
    3: "HIT",
    4: "HIT",
    5: "HIT",
    6: "HIT",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT",
    },
    7: {
    2: "HIT",
    3: "HIT",
    4: "HIT",
    5: "HIT",
    6: "HIT",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT",
    },
    6: {
    2: "HIT",
    3: "HIT",
    4: "HIT",
    5: "HIT",
    6: "HIT",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT",
    },
    5: {
    2: "HIT",
    3: "HIT",
    4: "HIT",
    5: "HIT",
    6: "HIT",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT",
    },
    4: {
    2: "HIT",
    3: "HIT",
    4: "HIT",
    5: "HIT",
    6: "HIT",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT",
    },
}
softTotalDict = {
    9: {
    2: "STAND",
    3: "STAND",
    4: "STAND",
    5: "STAND",
    6: "STAND",
    7: "STAND",
    8: "STAND",
    9: "STAND",
    10: "STAND",
    11: "STAND"
    },
    8: {
    2: "STAND",
    3: "STAND",
    4: "STAND",
    5: "STAND",
    6: "DOUBLE DOWN",
    7: "STAND",
    8: "STAND",
    9: "STAND",
    10: "STAND",
    11: "STAND"
    },
    7: {
    2: "DOUBLE DOWN",
    3: "DOUBLE DOWN",
    4: "DOUBLE DOWN",
    5: "DOUBLE DOWN",
    6: "DOUBLE DOWN",
    7: "STAND",
    8: "STAND",
    9: "HIT",
    10: "HIT",
    11: "HIT"
    },
    6: {
    2: "HIT",
    3: "DOUBLE DOWN",
    4: "DOUBLE DOWN",
    5: "DOUBLE DOWN",
    6: "DOUBLE DOWN",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT"
    },
    5: {
    2: "HIT",
    3: "HIT",
    4: "DOUBLE DOWN",
    5: "DOUBLE DOWN",
    6: "DOUBLE DOWN",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT"
    },
    4: {
    2: "HIT",
    3: "HIT",
    4: "DOUBLE DOWN",
    5: "DOUBLE DOWN",
    6: "DOUBLE DOWN",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT"
    },
    3: {
    2: "HIT",
    3: "HIT",
    4: "HIT",
    5: "DOUBLE DOWN",
    6: "DOUBLE DOWN",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT"
    },
    2: {
    2: "HIT",
    3: "HIT",
    4: "HIT",
    5: "DOUBLE DOWN",
    6: "DOUBLE DOWN",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT"
    }
}
pairSplittingDict = {
    11: {
    2: "SPLIT",
    3: "SPLIT",
    4: "SPLIT",
    5: "SPLIT",
    6: "SPLIT",
    7: "SPLIT",
    8: "SPLIT",
    9: "SPLIT",
    10: "SPLIT",
    11: "SPLIT"
    },
    10: {
    2: "STAND",
    3: "STAND",
    4: "STAND",
    5: "STAND",
    6: "STAND",
    7: "STAND",
    8: "STAND",
    9: "STAND",
    10: "STAND",
    11: "STAND"
    },
    9: {
    2: "SPLIT",
    3: "SPLIT",
    4: "SPLIT",
    5: "SPLIT",
    6: "SPLIT",
    7: "STAND",
    8: "SPLIT",
    9: "SPLIT",
    10: "STAND",
    11: "STAND"
    },
    8: {
    2: "SPLIT",
    3: "SPLIT",
    4: "SPLIT",
    5: "SPLIT",
    6: "SPLIT",
    7: "SPLIT",
    8: "SPLIT",
    9: "SPLIT",
    10: "SPLIT",
    11: "SPLIT"
    },
    7: {
    2: "SPLIT",
    3: "SPLIT",
    4: "SPLIT",
    5: "SPLIT",
    6: "SPLIT",
    7: "SPLIT",
    8: "HIT", 
    9: "HIT",
    10: "HIT",
    11: "HIT"
    },
    6: {
    2: "SPLIT AND DOUBLE DOWN",
    3: "SPLIT",
    4: "SPLIT",
    5: "SPLIT",
    6: "SPLIT",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT"
    },
    5: {
    2: "HIT",
    3: "HIT",
    4: "HIT",
    5: "HIT",
    6: "HIT",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT"
    },
    4: {
    2: "HIT",
    3: "HIT",
    4: "HIT",
    5: "SPLIT AND DOUBLE DOWN",
    6: "SPLIT AND DOUBLE DOWN",
    7: "HIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT"
    },
    3: {
    2: "SPLIT AND DOUBLE DOWN",
    3: "SPLIT AND DOUBLE DOWN",
    4: "SPLIT",
    5: "SPLIT",
    6: "SPLIT",
    7: "SPLIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT"
    },
    2: {
    2: "SPLIT AND DOUBLE DOWN",
    3: "SPLIT AND DOUBLE DOWN",
    4: "SPLIT",
    5: "SPLIT",
    6: "SPLIT",
    7: "SPLIT",
    8: "HIT",
    9: "HIT",
    10: "HIT",
    11: "HIT"
    }
}
